USE [master]
GO

/****** Object:  Database [Patient_TBI]    Script Date: 07/16/2013 18:01:26 ******/
CREATE DATABASE [Patient_TBI] ON  PRIMARY 
( NAME = N'Patient_TBI', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.NEWMSSQLSERVER\MSSQL\DATA\Patient_TBI.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Patient_TBI_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.NEWMSSQLSERVER\MSSQL\DATA\Patient_TBI_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Patient_TBI] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Patient_TBI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Patient_TBI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Patient_TBI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Patient_TBI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Patient_TBI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Patient_TBI] SET ARITHABORT OFF 
GO

ALTER DATABASE [Patient_TBI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Patient_TBI] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Patient_TBI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Patient_TBI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Patient_TBI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Patient_TBI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Patient_TBI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Patient_TBI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Patient_TBI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Patient_TBI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Patient_TBI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Patient_TBI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Patient_TBI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Patient_TBI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Patient_TBI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Patient_TBI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Patient_TBI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Patient_TBI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Patient_TBI] SET  READ_WRITE 
GO

ALTER DATABASE [Patient_TBI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Patient_TBI] SET  MULTI_USER 
GO

ALTER DATABASE [Patient_TBI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Patient_TBI] SET DB_CHAINING OFF 
GO

